export const softwarehouseGateSpecs = [
  {
    project: "Soar/Roost",
    rootBlocker: "LUC-30",
    owner: "09 DRE (Deployment & Reliability Engineer)",
    purpose: "VPS/Coolify deployment path and read-only production resource observation for Soar and Roost.",
    approvalPurpose: "read-only Coolify deployment/resource status recheck",
    allowedAction: "One read-only Coolify project/resource/deployment status recheck after current Coolify credential/resource metadata is present.",
    forbiddenAction: "No deploy trigger, restart, rollback, env mutation, push, shell mutation, or unrelated production probing.",
    evidenceRequired: "Coolify project/team/resource metadata presence, exact read-only command or UI path, timestamp, resource statuses, and any unhealthy resource.",
    acceptedFreshFacts: [
      "Coolify read token, team, project, environment, and resource ids are bound to the responsible runtime as secret refs.",
      "A fresh Coolify reconciler run records pass/fail status for Soar/Roost resources without exposing secret values.",
      "Explicit issue comment approving one read-only Coolify deployment/status recheck.",
    ],
    operatorPrompt:
      "Ensure Coolify read-only metadata is available through Paperclip secret refs; then allow exactly one deployment/resource status recheck and route any unhealthy resource to DRE/QVE/SPA.",
    approvalDryRunCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-30",
    approvalApplyCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-30 --apply",
    recheckHandoff:
      "After current Coolify metadata exists, 09 DRE may run exactly one read-only Coolify status/log/resource recheck, then must post pass/fail evidence and route any unhealthy resource without mutating production.",
    resumeComment: [
      "Coolify runtime metadata is available through Paperclip secret refs.",
      "Resume exactly one read-only Coolify deployment/resource status recheck.",
      "No deploy, restart, rollback, env mutation, push, shell mutation, or unrelated production probing.",
      "Close with resource status evidence and route any unhealthy resource to a concrete DRE/QVE/SPA repair lane.",
    ].join("\n"),
    secretKeys: [
      "coolify_base_url",
      "coolify_api_token",
      "coolify_token",
      "coolify_team_id",
      "coolify_soar_team_id",
      "coolify_soar_project_id",
      "coolify_soar_project_uuid",
      "coolify_soar_production_environment",
      "coolify_soar_app_id",
      "coolify_soar_api_app_id",
      "coolify_soar_web_app_id",
      "coolify_soar_worker_backtest_app_id",
      "coolify_soar_worker_execution_app_id",
      "coolify_soar_worker_market_data_app_id",
      "coolify_soar_worker_market_stream_app_id",
      "coolify_soar_postgres_resource_id",
      "coolify_soar_redis_resource_id",
      "coolify_roost_app_id",
    ],
  },
  {
    project: "Soar/Roost",
    rootBlocker: "LUC-31",
    owner: "09 QVE (QA & Verification Engineer)",
    purpose: "Production readiness verification for Soar and Roost through non-destructive smoke/user-flow proof.",
    approvalPurpose: "non-destructive production smoke/readiness recheck",
    allowedAction: "One non-destructive smoke/readiness recheck after app test-account metadata or owner-approved read-only proof path is present.",
    forbiddenAction: "No deploy, restart, production data mutation, live trading/order action, destructive Roost file operation, secret disclosure, or unrelated probing.",
    evidenceRequired: "Smoke account metadata presence, exact command or UI path, timestamp, endpoint/workflow tested, pass/fail result, and next blocker if any.",
    acceptedFreshFacts: [
      "Soar or Roost production smoke credentials are bound as secret refs for the responsible verifier.",
      "A fresh production smoke/readiness run records pass/fail evidence without exposing credentials.",
      "Explicit issue comment approving one protected production smoke recheck.",
    ],
    operatorPrompt:
      "Ensure dedicated Soar/Roost smoke-account refs are available; then allow exactly one non-destructive smoke/readiness recheck and record evidence.",
    approvalDryRunCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-31",
    approvalApplyCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-31 --apply",
    recheckHandoff:
      "After current smoke-account metadata exists, 09 QVE may run exactly one non-destructive production readiness recheck and must post pass/fail evidence.",
    resumeComment: [
      "Production smoke metadata is available through Paperclip secret refs.",
      "Resume exactly one non-destructive production readiness recheck.",
      "No deploy, restart, production data mutation, LIVE trading/order action, destructive Roost file operation, secret disclosure, or unrelated probing.",
      "Close with endpoint/workflow pass/fail evidence and return to blocked if the smoke path still fails.",
    ].join("\n"),
    secretKeys: [
      "soar_prod_base_url",
      "soar_api_base_url",
      "soar_prod_test_email",
      "soar_prod_test_password",
      "soar_prod_admin_smoke_email",
      "soar_prod_admin_smoke_password",
      "roost_prod_base_url",
      "roost_api_base_url",
      "roost_prod_test_email",
      "roost_prod_test_password",
      "roost_prod_test_workspace_name",
      "smoke_auth_email",
      "smoke_auth_password",
    ],
  },
  {
    project: "Soar/Roost",
    rootBlocker: "LUC-32",
    owner: "10 SPA (Security & Privacy Auditor)",
    purpose: "Security, secrets, and production-safety gate for Soar/Roost release and protected operations.",
    approvalPurpose: "redacted security/secret metadata and safety-gate recheck",
    allowedAction: "One redacted secret/resource metadata and safety-policy recheck after current Paperclip secret refs are bound.",
    forbiddenAction: "No raw secret exposure, secret rotation, production mutation, deploy/restart, paid service change, legal/customer/finance commitment, or LIVE trading/order proof.",
    evidenceRequired: "Names-only secret/resource readiness, least-privilege binding scope, timestamp, safety decision, and residual risk.",
    acceptedFreshFacts: [
      "Current Coolify/readiness/smoke secret refs are present and bound with least-privilege runtime scope.",
      "A fresh SPA/DRE/QVE safety recheck records names-only readiness and any remaining protected-action blockers.",
      "Explicit issue comment approving one redacted safety-gate recheck.",
    ],
    operatorPrompt:
      "Verify secret refs and least-privilege runtime access by metadata only; do not expose values, mutate secrets, or approve destructive production actions.",
    approvalDryRunCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-32",
    approvalApplyCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-32 --apply",
    recheckHandoff:
      "After current secret/resource metadata exists, 10 SPA may run exactly one redacted safety-gate recheck and must post names-only evidence plus residual risk.",
    resumeComment: [
      "Security and secret metadata is available through Paperclip secret refs.",
      "Resume exactly one redacted safety-gate recheck.",
      "No raw secret exposure, secret rotation, production mutation, deploy/restart, paid service change, legal/customer/finance commitment, or LIVE trading/order proof.",
      "Close with names-only binding evidence and residual risk.",
    ].join("\n"),
    secretKeys: [
      "coolify_read_api_token",
      "coolify_deploy_api_token",
      "coolify_base_url",
      "coolify_api_url",
      "coolify_team_id_luckysparrow",
      "coolify_project_id_soar",
      "coolify_project_uuid_soar",
      "coolify_environment_uuid_soar_production",
      "coolify_resource_uuid_soar_web",
      "coolify_resource_uuid_soar_api",
      "coolify_resource_uuid_roost_app",
      "soar_prod_base_url",
      "soar_api_base_url",
      "roost_prod_base_url",
      "roost_api_base_url",
    ],
  },
];

export const softwarehouseGateSpecsByRootBlocker = new Map(
  softwarehouseGateSpecs.map((spec) => [spec.rootBlocker, spec]),
);
