export const softwarehouseGateSpecs = [
  {
    project: "Soar",
    rootBlocker: "LUC-241",
    owner: "09 DRE (Deployment & Reliability Engineer)",
    purpose: "Protected workers/readiness smoke and authenticated proof for Soar.",
    approvalPurpose: "read-only protected `/workers/ready` auth/smoke recheck",
    allowedAction: "One read-only auth/smoke recheck after fresh credential metadata, standing autonomous approval, or explicit operator approval.",
    forbiddenAction: "No deploy, restart, runtime mutation, push, live-account mutation, or unrelated production probing.",
    evidenceRequired: "Smoke/auth result, exact command or UI path, timestamp, affected endpoint, and fail/pass reason.",
    acceptedFreshFacts: [
      "Operator-approved new smoke/admin session or token recorded after the current blocker timestamp.",
      "A credential rotation/update for one of the tracked auth secrets, recorded as an explicit operator/board fact after the current blocker timestamp.",
      "A softwarehouse-autonomous-gate-approval comment generated by the control loop after verifying tracked credential metadata and cooldown.",
      "Explicit issue comment approving one read-only protected `/workers/ready` recheck.",
      "A new deploy/build fact that changes the tested auth path and is explicitly tied to this gate.",
    ],
    operatorPrompt:
      "Ensure a valid Soar production admin/smoke principal is available to the execution session; the control loop may approve one narrow read-only `/workers/ready` recheck autonomously when credential metadata is present and cooldown permits.",
    approvalDryRunCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-241",
    approvalApplyCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-241 --apply",
    recheckHandoff:
      "After a fresh approval/credential fact exists, 09 DRE (Deployment & Reliability Engineer) may run exactly one protected smoke/auth recheck, then must post pass/fail evidence and return the gate to blocked if it still fails.",
    resumeComment: [
      "Gate freshness watcher detected newer Soar credential metadata, standing autonomous approval, or explicit operator approval after the latest blocker.",
      "Resume exactly one read-only auth/smoke recheck for protected `/workers/ready`.",
      "No deploy, restart, runtime mutation, push, live-account mutation, or unrelated production probing.",
      "Close with smoke/auth evidence and return to `blocked` if the credential/session path still fails.",
    ].join("\n"),
    secretKeys: [
      "smoke_auth_token",
      "smoke_auth_email",
      "smoke_auth_password",
      "prod_ui_audit_auth_token",
      "prod_ui_audit_auth_email",
      "prod_ui_audit_auth_password",
      "prod_ui_audit_admin_token",
      "prod_ui_audit_admin_email",
      "prod_ui_audit_admin_password",
    ],
  },
  {
    project: "Roost",
    rootBlocker: "LUC-261",
    owner: "11 RPM (Roost Project Manager)",
    purpose: "Active local delivery and protected deploy-smoke baseline for Roost / CompanyCore.",
    approvalPurpose: "protected Roost/CompanyCore smoke recheck",
    allowedAction: "One protected smoke recheck after approved CompanyCore credential metadata, standing autonomous approval, or explicit operator approval.",
    forbiddenAction: "No product-code mutation, push, deploy expansion, or unrelated runtime change.",
    evidenceRequired: "CompanyCore key/base-url presence proof without values, smoke result, timestamp, and next blocker if any.",
    acceptedFreshFacts: [
      "Operator-approved CompanyCore API key/base URL metadata recorded after the current blocker timestamp.",
      "A credential rotation/update for `companycore_api_key` or `companycore_base_url`, recorded as an explicit operator/board fact after the current blocker timestamp.",
      "A softwarehouse-autonomous-gate-approval comment generated by the control loop after verifying tracked credential metadata and cooldown.",
      "Explicit issue comment approving one protected Roost deploy-smoke recheck.",
    ],
    operatorPrompt:
      "Ensure Roost/CompanyCore protected smoke credentials are available to the execution session; the control loop may approve one narrow protected deploy-smoke recheck autonomously when credential metadata is present and cooldown permits.",
    approvalDryRunCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-261",
    approvalApplyCommand: "node scripts/record-softwarehouse-gate-approval.mjs --gate=LUC-261 --apply",
    recheckHandoff:
      "After a fresh approval/credential fact exists, 11 RPM (Roost Project Manager) may run exactly one protected smoke recheck, then must post pass/fail evidence; local delivery may continue while protected production actions stay gated.",
    resumeComment: [
      "Gate freshness watcher detected newer Roost/CompanyCore credential metadata, standing autonomous approval, or explicit operator approval after the latest blocker.",
      "Resume exactly one protected deploy-smoke recheck with the approved `COMPANYCORE_API_KEY` path.",
      "No product-code mutation, push, deploy expansion, or unrelated runtime change.",
      "Close with smoke evidence and return to `blocked` if the protected key is absent or invalid.",
    ].join("\n"),
    secretKeys: [
      "companycore_api_key",
      "companycore_base_url",
    ],
  },
  {
    project: "Soar",
    rootBlocker: "LUC-3924",
    owner: "09 IDE (Integration Domain Engineer)",
    purpose: "LIVEIMPORT_READBACK protected read-only import/runtime evidence for Soar ARB-006.",
    approvalPurpose: "read-only LIVEIMPORT_READBACK protected collector recheck",
    allowedAction: "One read-only LIVEIMPORT_READBACK collector recheck after encrypted alias bindings are present for the responsible runner.",
    forbiddenAction: "No deploy, restart, runtime mutation, push, live-account mutation, secret disclosure, exchange action, or unrelated production probing.",
    evidenceRequired: "Names-only env readiness, collector command, timestamp, production build SHA, protected readback pass/fail reason, and fail-closed blocker if any.",
    acceptedFreshFacts: [
      "Encrypted prod_ui_audit secret aliases are bound to LIVEIMPORT_READBACK_* env names for the responsible runner after the latest missing-env blocker.",
      "Operator-approved production read-only app principal metadata exists in Paperclip secrets without exposing secret values.",
      "A fresh collector run records names-only env readiness and protected readback evidence after the binding repair.",
    ],
    operatorPrompt:
      "Bind LIVEIMPORT_READBACK_* env names to existing encrypted prod_ui_audit aliases for the AIA/IDE runner context, then wake exactly one LUC-1754 collector rerun.",
    approvalDryRunCommand: "node scripts/repair-runtime-gate-bindings.mjs --gate=LUC-3924",
    approvalApplyCommand: "node scripts/repair-runtime-gate-bindings.mjs --gate=LUC-3924 --apply",
    recheckHandoff:
      "After binding repair, Integration Domain Engineer may run exactly one protected LIVEIMPORT_READBACK collector proof, then must post pass/fail evidence and return to blocked if auth/readback still fails.",
    resumeComment: [
      "LIVEIMPORT_READBACK encrypted alias bindings are available for the responsible runner.",
      "Run exactly one read-only collector recheck for LUC-1754 and record names-only readiness plus pass/fail evidence.",
      "No deploy, restart, runtime mutation, push, live-account mutation, secret disclosure, exchange action, or unrelated production probing.",
    ].join("\n"),
    secretKeys: [
      "liveimport_readback_api_base_url",
      "liveimport_readback_web_base_url",
      "liveimport_readback_expected_sha",
      "liveimport_readback_auth_token",
      "liveimport_readback_auth_email",
      "liveimport_readback_auth_password",
      "liveimport_readback_ops_auth_header_name",
      "liveimport_readback_ops_auth_header_value",
      "liveimport_readback_ops_basic_user",
      "liveimport_readback_ops_basic_password",
    ],
  },
];

export const softwarehouseGateSpecsByRootBlocker = new Map(
  softwarehouseGateSpecs.map((spec) => [spec.rootBlocker, spec]),
);
