import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgTable, real, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { agents } from "./agents.js";
import { companies } from "./companies.js";
import { heartbeatRuns } from "./heartbeat_runs.js";
import { issues } from "./issues.js";
import { supervisionCycles } from "./supervision.js";

export const operationalConstraints = pgTable("operational_constraints", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("active"),
  title: text("title").notNull(),
  rationale: text("rationale").notNull(),
  affectedCount: integer("affected_count").notNull().default(0),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  evidence: jsonb("evidence").$type<Array<Record<string, unknown>>>().notNull().default([]),
  affectedIssueIds: jsonb("affected_issue_ids").$type<string[]>().notNull().default([]),
  proposedResponse: jsonb("proposed_response").$type<Record<string, unknown>>().notNull().default({}),
  flowSlo: jsonb("flow_slo").$type<Record<string, unknown>>().notNull().default({}),
  resolutionCriteria: jsonb("resolution_criteria").$type<Array<Record<string, unknown>>>().notNull().default([]),
  firstObservedAt: timestamp("first_observed_at", { withTimezone: true }).notNull().defaultNow(),
  lastObservedAt: timestamp("last_observed_at", { withTimezone: true }).notNull().defaultNow(),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyKeyUnique: uniqueIndex("operational_constraints_company_key_uq").on(table.companyId, table.key),
  companyStatusIdx: index("operational_constraints_company_status_idx").on(table.companyId, table.status, table.lastObservedAt),
  statusCheck: check("operational_constraints_status_check", sql`${table.status} in ('active','observing','resolved','superseded')`),
}));

export const autonomyEnvelopes = pgTable("autonomy_envelopes", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  actionClass: text("action_class").notNull(),
  stage: text("stage").notNull().default("SHADOW"),
  enabled: boolean("enabled").notNull().default(true),
  scope: jsonb("scope").$type<Record<string, unknown>>().notNull().default({}),
  budget: jsonb("budget").$type<Record<string, unknown>>().notNull().default({}),
  concurrency: jsonb("concurrency").$type<Record<string, unknown>>().notNull().default({}),
  allowedActions: jsonb("allowed_actions").$type<string[]>().notNull().default([]),
  rollback: jsonb("rollback").$type<Record<string, unknown>>().notNull().default({}),
  graduationPolicy: jsonb("graduation_policy").$type<Record<string, unknown>>().notNull().default({}),
  graduationMetrics: jsonb("graduation_metrics").$type<Record<string, unknown>>().notNull().default({}),
  downgradeReason: text("downgrade_reason"),
  version: integer("version").notNull().default(1),
  graduatedAt: timestamp("graduated_at", { withTimezone: true }),
  downgradedAt: timestamp("downgraded_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyKeyUnique: uniqueIndex("autonomy_envelopes_company_key_uq").on(table.companyId, table.key),
  companyStageIdx: index("autonomy_envelopes_company_stage_idx").on(table.companyId, table.stage, table.enabled),
  stageCheck: check("autonomy_envelopes_stage_check", sql`${table.stage} in ('SHADOW','RECOMMEND','LIMITED_AUTO','AUTO')`),
}));

export const autonomyDecisions = pgTable("autonomy_decisions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  cycleId: uuid("cycle_id").references(() => supervisionCycles.id, { onDelete: "set null" }),
  constraintId: uuid("constraint_id").references(() => operationalConstraints.id, { onDelete: "set null" }),
  envelopeId: uuid("envelope_id").references(() => autonomyEnvelopes.id, { onDelete: "set null" }),
  selectedIssueId: uuid("selected_issue_id").references(() => issues.id, { onDelete: "set null" }),
  stateDigest: text("state_digest").notNull(),
  sampleKey: text("sample_key").notNull(),
  sampleIdentity: jsonb("sample_identity").$type<Record<string, unknown>>().notNull().default({}),
  decisionModelVersion: text("decision_model_version").notNull().default("work-selection-v2.1"),
  calibrationCohort: text("calibration_cohort").notNull().default("work-selection-v2.1"),
  envelopeVersion: integer("envelope_version").notNull().default(1),
  actionClass: text("action_class").notNull(),
  mode: text("mode").notNull(),
  disposition: text("disposition").notNull(),
  reasonCode: text("reason_code").notNull(),
  candidates: jsonb("candidates").$type<Array<Record<string, unknown>>>().notNull().default([]),
  rejectedAlternatives: jsonb("rejected_alternatives").$type<Array<Record<string, unknown>>>().notNull().default([]),
  decisionVector: jsonb("decision_vector").$type<Record<string, unknown>>().notNull(),
  evidenceRefs: jsonb("evidence_refs").$type<Array<Record<string, unknown>>>().notNull().default([]),
  riskLevel: text("risk_level").notNull(),
  estimatedCost: jsonb("estimated_cost").$type<Record<string, unknown>>().notNull().default({}),
  expectedOutcome: jsonb("expected_outcome").$type<Record<string, unknown>>().notNull(),
  confidence: real("confidence").notNull(),
  evidenceFreshUntil: timestamp("evidence_fresh_until", { withTimezone: true }).notNull(),
  invalidationConditions: jsonb("invalidation_conditions").$type<string[]>().notNull().default([]),
  status: text("status").notNull().default("active"),
  invalidatedReason: text("invalidated_reason"),
  laterResult: jsonb("later_result").$type<Record<string, unknown>>(),
  operatorDecision: jsonb("operator_decision").$type<Record<string, unknown>>(),
  counterfactualEvidence: jsonb("counterfactual_evidence").$type<Array<Record<string, unknown>>>().notNull().default([]),
  decidedAt: timestamp("decided_at", { withTimezone: true }).notNull().defaultNow(),
  invalidatedAt: timestamp("invalidated_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyDigestUnique: uniqueIndex("autonomy_decisions_company_digest_uq").on(table.companyId, table.stateDigest, table.mode),
  companySampleIdx: index("autonomy_decisions_company_sample_idx").on(table.companyId, table.sampleKey, table.decisionModelVersion),
  companyStatusIdx: index("autonomy_decisions_company_status_idx").on(table.companyId, table.status, table.decidedAt),
  issueIdx: index("autonomy_decisions_issue_idx").on(table.selectedIssueId, table.decidedAt),
  modeCheck: check("autonomy_decisions_mode_check", sql`${table.mode} in ('SHADOW','RECOMMEND','LIMITED_AUTO','AUTO')`),
  statusCheck: check("autonomy_decisions_status_check", sql`${table.status} in ('active','invalidated','dispatched','completed','failed','no_action')`),
  confidenceCheck: check("autonomy_decisions_confidence_check", sql`${table.confidence} >= 0 and ${table.confidence} <= 1`),
}));

export const autonomyDecisionEvaluations = pgTable("autonomy_decision_evaluations", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  decisionId: uuid("decision_id").notNull().references(() => autonomyDecisions.id, { onDelete: "cascade" }),
  evaluatorSource: text("evaluator_source").notNull(),
  signalType: text("signal_type").notNull().default("ORACLE_VERDICT"),
  evaluatorMetadata: jsonb("evaluator_metadata").$type<Record<string, unknown>>().notNull().default({}),
  evidenceAvailable: jsonb("evidence_available").$type<Array<Record<string, unknown>>>().notNull().default([]),
  verdict: text("verdict").notNull(),
  alternativeIssueId: uuid("alternative_issue_id").references(() => issues.id, { onDelete: "set null" }),
  rationale: text("rationale").notNull(),
  evidenceRefs: jsonb("evidence_refs").$type<Array<Record<string, unknown>>>().notNull().default([]),
  actualOutcomeQuality: text("actual_outcome_quality"),
  evaluatedAt: timestamp("evaluated_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  decisionEvaluatorUnique: uniqueIndex("autonomy_decision_evaluations_decision_evaluator_uq").on(table.decisionId, table.evaluatorSource),
  companyVerdictIdx: index("autonomy_decision_evaluations_company_verdict_idx").on(table.companyId, table.verdict, table.evaluatedAt),
  verdictCheck: check("autonomy_decision_evaluations_verdict_check", sql`${table.verdict} in ('agree','disagree','insufficient_evidence','alternative','unsafe','stale_state')`),
  signalTypeCheck: check("autonomy_decision_evaluations_signal_type_check", sql`${table.signalType} in ('ORACLE_VERDICT','OPERATOR_DECISION','COUNTERFACTUAL_WEAK_EVIDENCE')`),
}));

export const autonomyExecutions = pgTable("autonomy_executions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  decisionId: uuid("decision_id").notNull().references(() => autonomyDecisions.id, { onDelete: "cascade" }),
  canaryAuthorizationId: uuid("canary_authorization_id"),
  issueId: uuid("issue_id").notNull().references(() => issues.id, { onDelete: "cascade" }),
  runId: uuid("run_id").references(() => heartbeatRuns.id, { onDelete: "set null" }),
  idempotencyKey: text("idempotency_key").notNull(),
  status: text("status").notNull().default("PENDING"),
  livenessStatus: text("liveness_status").notNull().default("STARTING"),
  livenessPolicy: jsonb("liveness_policy").$type<Record<string, unknown>>().notNull().default({}),
  preemptionClass: text("preemption_class").notNull().default("SAFE_POINT_ONLY"),
  preconditionSnapshot: jsonb("precondition_snapshot").$type<Record<string, unknown>>().notNull(),
  dispatchPostcondition: jsonb("dispatch_postcondition").$type<Record<string, unknown>>(),
  executionPostcondition: jsonb("execution_postcondition").$type<Record<string, unknown>>(),
  outcomeVerification: jsonb("outcome_verification").$type<Record<string, unknown>>(),
  predictedImpact: jsonb("predicted_impact").$type<Record<string, unknown>>().notNull().default({}),
  actualImpact: jsonb("actual_impact").$type<Record<string, unknown>>(),
  constraintImpactStatus: text("constraint_impact_status"),
  constraintImpactEvidence: jsonb("constraint_impact_evidence").$type<Array<Record<string, unknown>>>().notNull().default([]),
  costCoverage: jsonb("cost_coverage").$type<Record<string, unknown>>().notNull().default({}),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyIdempotencyUnique: uniqueIndex("autonomy_executions_company_idempotency_uq").on(table.companyId, table.idempotencyKey),
  decisionUnique: uniqueIndex("autonomy_executions_decision_uq").on(table.decisionId),
  companyStatusIdx: index("autonomy_executions_company_status_idx").on(table.companyId, table.status, table.updatedAt),
  statusCheck: check("autonomy_executions_status_check", sql`${table.status} in ('PENDING','ACCEPTED','FAILED','UNCERTAIN','RUNNING','COMPLETED','OUTCOME_VERIFIED','OUTCOME_FAILED')`),
  livenessStatusCheck: check("autonomy_executions_liveness_status_check", sql`${table.livenessStatus} in ('STARTING','RUNNING','WAITING_VALID','STALLED','UNCERTAIN','TERMINAL')`),
  preemptionClassCheck: check("autonomy_executions_preemption_class_check", sql`${table.preemptionClass} in ('PREEMPTIBLE','SAFE_POINT_ONLY','NON_PREEMPTIBLE')`),
  impactStatusCheck: check("autonomy_executions_constraint_impact_status_check", sql`${table.constraintImpactStatus} is null or ${table.constraintImpactStatus} in ('SUPPORTED','AMBIGUOUS','CONTRADICTED','NOT_MEASURABLE')`),
}));

export const issueIntents = pgTable("issue_intents", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  issueId: uuid("issue_id").notNull().references(() => issues.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("UNKNOWN"),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  validUntil: timestamp("valid_until", { withTimezone: true }),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  ownerUserId: text("owner_user_id"),
  source: text("source").notNull(),
  reason: text("reason").notNull(),
  hierarchy: jsonb("hierarchy").$type<Record<string, unknown>>().notNull().default({}),
  canonicalOwner: text("canonical_owner").notNull().default("paperclip"),
  targetCanonicalOwner: text("target_canonical_owner").notNull().default("roost"),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyIssueUnique: uniqueIndex("issue_intents_company_issue_uq").on(table.companyId, table.issueId),
  companyStatusIdx: index("issue_intents_company_status_idx").on(table.companyId, table.status, table.validUntil),
  statusCheck: check("issue_intents_status_check", sql`${table.status} in ('ACTIVE','RECONFIRM_REQUIRED','SUPERSEDED','OBSOLETE','SATISFIED_ELSEWHERE','UNKNOWN')`),
}));

export const autonomyCanaryAuthorizations = pgTable("autonomy_canary_authorizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  envelopeId: uuid("envelope_id").notNull().references(() => autonomyEnvelopes.id, { onDelete: "cascade" }),
  decisionId: uuid("decision_id").references(() => autonomyDecisions.id, { onDelete: "set null" }),
  actionClass: text("action_class").notNull(),
  candidateCriteria: jsonb("candidate_criteria").$type<Record<string, unknown>>().notNull(),
  maxExecutions: integer("max_executions").notNull().default(1),
  usedExecutions: integer("used_executions").notNull().default(0),
  maxConcurrency: integer("max_concurrency").notNull().default(1),
  allowedRisk: jsonb("allowed_risk").$type<string[]>().notNull().default(["low"]),
  environments: jsonb("environments").$type<string[]>().notNull().default(["local"]),
  budget: jsonb("budget").$type<Record<string, unknown>>().notNull().default({}),
  validFrom: timestamp("valid_from", { withTimezone: true }).notNull().defaultNow(),
  validUntil: timestamp("valid_until", { withTimezone: true }).notNull(),
  rollbackRequirement: jsonb("rollback_requirement").$type<Record<string, unknown>>().notNull(),
  verificationRequirement: jsonb("verification_requirement").$type<Record<string, unknown>>().notNull(),
  issuerType: text("issuer_type").notNull(),
  issuerId: text("issuer_id").notNull(),
  rationale: text("rationale").notNull(),
  stopConditions: jsonb("stop_conditions").$type<string[]>().notNull().default([]),
  experiment: jsonb("experiment").$type<Record<string, unknown>>().notNull(),
  status: text("status").notNull().default("ACTIVE"),
  stoppedReason: text("stopped_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyStatusIdx: index("autonomy_canary_authorizations_company_status_idx").on(table.companyId, table.status, table.validUntil),
  decisionIdx: index("autonomy_canary_authorizations_decision_idx").on(table.decisionId),
  statusCheck: check("autonomy_canary_authorizations_status_check", sql`${table.status} in ('ACTIVE','EXHAUSTED','EXPIRED','STOPPED','REVOKED')`),
  issuerCheck: check("autonomy_canary_authorizations_issuer_check", sql`${table.issuerType} in ('user','system')`),
  boundedExecutionsCheck: check("autonomy_canary_authorizations_execution_limit_check", sql`${table.maxExecutions} > 0 and ${table.usedExecutions} >= 0 and ${table.usedExecutions} <= ${table.maxExecutions}`),
}));

export const autonomyInterrupts = pgTable("autonomy_interrupts", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  severity: text("severity").notNull(),
  scope: jsonb("scope").$type<Record<string, unknown>>().notNull(),
  source: text("source").notNull(),
  evidence: jsonb("evidence").$type<Array<Record<string, unknown>>>().notNull().default([]),
  preemptibleWorkClasses: jsonb("preemptible_work_classes").$type<string[]>().notNull().default([]),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  status: text("status").notNull().default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyStatusIdx: index("autonomy_interrupts_company_status_idx").on(table.companyId, table.status, table.expiresAt),
  statusCheck: check("autonomy_interrupts_status_check", sql`${table.status} in ('ACTIVE','EXPIRED','CLEARED','REVALIDATION_REQUIRED')`),
  severityCheck: check("autonomy_interrupts_severity_check", sql`${table.severity} in ('info','warning','critical')`),
}));

export const learnedPolicies = pgTable("learned_policies", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  version: integer("version").notNull().default(1),
  lifecycle: text("lifecycle").notNull().default("PROPOSED"),
  scope: jsonb("scope").$type<Record<string, unknown>>().notNull(),
  provenance: jsonb("provenance").$type<Record<string, unknown>>().notNull(),
  confidence: real("confidence").notNull(),
  expectedEffect: jsonb("expected_effect").$type<Record<string, unknown>>().notNull(),
  observedEffect: jsonb("observed_effect").$type<Record<string, unknown>>().notNull().default({}),
  rollbackCondition: jsonb("rollback_condition").$type<Record<string, unknown>>().notNull(),
  supersedesPolicyId: uuid("supersedes_policy_id"),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  reviewAt: timestamp("review_at", { withTimezone: true }),
  canonicalOwner: text("canonical_owner").notNull().default("paperclip"),
  targetCanonicalOwner: text("target_canonical_owner").notNull().default("roost"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyKeyVersionUnique: uniqueIndex("learned_policies_company_key_version_uq").on(table.companyId, table.key, table.version),
  companyLifecycleIdx: index("learned_policies_company_lifecycle_idx").on(table.companyId, table.lifecycle, table.reviewAt),
  lifecycleCheck: check("learned_policies_lifecycle_check", sql`${table.lifecycle} in ('PROPOSED','EXPERIMENTAL','ACTIVE','SUSPECT','ROLLED_BACK','SUPERSEDED','RETIRED')`),
  confidenceCheck: check("learned_policies_confidence_check", sql`${table.confidence} >= 0 and ${table.confidence} <= 1`),
}));

export const policyExceptions = pgTable("policy_exceptions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  policyId: uuid("policy_id").notNull().references(() => learnedPolicies.id, { onDelete: "cascade" }),
  scope: jsonb("scope").$type<Record<string, unknown>>().notNull(),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  ownerUserId: text("owner_user_id"),
  rationale: text("rationale").notNull(),
  riskAcceptance: text("risk_acceptance").notNull(),
  evidence: jsonb("evidence").$type<Array<Record<string, unknown>>>().notNull().default([]),
  validUntil: timestamp("valid_until", { withTimezone: true }).notNull(),
  status: text("status").notNull().default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyStatusIdx: index("policy_exceptions_company_status_idx").on(table.companyId, table.status, table.validUntil),
  statusCheck: check("policy_exceptions_status_check", sql`${table.status} in ('ACTIVE','EXPIRED','REVOKED','USED')`),
}));
