import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { admissionDecisions } from "./admission_decisions.js";
import { agents } from "./agents.js";
import { companies } from "./companies.js";
import { deliveryTasks } from "./delivery_tasks.js";
import { heartbeatRuns } from "./heartbeat_runs.js";
import { issues } from "./issues.js";
import { productDeliveries } from "./product_deliveries.js";
import { projects } from "./projects.js";

export const supervisionRootCauses = pgTable("supervision_root_causes", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  fingerprint: text("fingerprint").notNull(),
  problemClass: text("problem_class").notNull(),
  status: text("status").notNull().default("hypothesis"),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  hypothesis: text("hypothesis"),
  resolution: text("resolution"),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  ownerUserId: text("owner_user_id"),
  projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }),
  issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  retainedUntil: timestamp("retained_until", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyFingerprintUq: uniqueIndex("supervision_root_causes_company_fingerprint_uq").on(table.companyId, table.fingerprint),
  companyStatusIdx: index("supervision_root_causes_company_status_idx").on(table.companyId, table.status, table.updatedAt),
  ownerIdx: index("supervision_root_causes_owner_idx").on(table.ownerAgentId, table.status),
}));

export const nativeSafeguards = pgTable("native_safeguards", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  key: text("key").notNull(),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("proposed"),
  title: text("title").notNull(),
  target: text("target").notNull(),
  implementationRef: text("implementation_ref"),
  regressionTestRef: text("regression_test_ref"),
  removalCondition: text("removal_condition"),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  rootCauseId: uuid("root_cause_id").references(() => supervisionRootCauses.id, { onDelete: "set null" }),
  version: integer("version").notNull().default(1),
  enabled: boolean("enabled").notNull().default(false),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  retiredAt: timestamp("retired_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyKeyUq: uniqueIndex("native_safeguards_company_key_uq").on(table.companyId, table.key),
  companyStatusIdx: index("native_safeguards_company_status_idx").on(table.companyId, table.status, table.updatedAt),
  rootCauseIdx: index("native_safeguards_root_cause_idx").on(table.rootCauseId),
}));

export const supervisionFindings = pgTable("supervision_findings", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  fingerprint: text("fingerprint").notNull(),
  problemClass: text("problem_class").notNull(),
  severity: text("severity").notNull().default("warning"),
  status: text("status").notNull().default("detected"),
  classification: text("classification").notNull().default("unclassified"),
  sourceKind: text("source_kind").notNull(),
  sourceRef: text("source_ref"),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  affectedComponent: text("affected_component"),
  projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }),
  issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
  deliveryId: uuid("delivery_id").references(() => productDeliveries.id, { onDelete: "set null" }),
  deliveryTaskId: uuid("delivery_task_id").references(() => deliveryTasks.id, { onDelete: "set null" }),
  affectedAgentId: uuid("affected_agent_id").references(() => agents.id, { onDelete: "set null" }),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  ownerUserId: text("owner_user_id"),
  admissionDecisionId: uuid("admission_decision_id").references(() => admissionDecisions.id, { onDelete: "set null" }),
  rootCauseId: uuid("root_cause_id").references(() => supervisionRootCauses.id, { onDelete: "set null" }),
  nativeSafeguardId: uuid("native_safeguard_id").references(() => nativeSafeguards.id, { onDelete: "set null" }),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  recurrenceCount: integer("recurrence_count").notNull().default(0),
  retryCount: integer("retry_count").notNull().default(0),
  economics: jsonb("economics").$type<Record<string, unknown>>().notNull().default({}),
  decision: jsonb("decision").$type<Record<string, unknown>>().notNull().default({}),
  recoveryState: text("recovery_state").notNull().default("healthy"),
  bottleneckType: text("bottleneck_type"),
  bottleneckStartedAt: timestamp("bottleneck_started_at", { withTimezone: true }),
  bottleneckStage: text("bottleneck_stage"),
  dependency: text("dependency"),
  slaDueAt: timestamp("sla_due_at", { withTimezone: true }),
  nextAllowedAction: text("next_allowed_action"),
  escalationCondition: text("escalation_condition"),
  bottleneckResolvedAt: timestamp("bottleneck_resolved_at", { withTimezone: true }),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  cooldownUntil: timestamp("cooldown_until", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  retainedUntil: timestamp("retained_until", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyFingerprintUq: uniqueIndex("supervision_findings_company_fingerprint_uq").on(table.companyId, table.fingerprint),
  companyStatusIdx: index("supervision_findings_company_status_idx").on(table.companyId, table.status, table.severity, table.updatedAt),
  ownerIdx: index("supervision_findings_owner_idx").on(table.ownerAgentId, table.status),
  projectIdx: index("supervision_findings_project_idx").on(table.projectId, table.status),
  rootCauseIdx: index("supervision_findings_root_cause_idx").on(table.rootCauseId, table.status),
  deliveryIdx: index("supervision_findings_delivery_idx").on(table.deliveryId, table.status),
  bottleneckIdx: index("supervision_findings_bottleneck_idx").on(table.companyId, table.bottleneckType, table.slaDueAt),
}));

export const supervisionCycles = pgTable("supervision_cycles", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  sourceKind: text("source_kind").notNull(),
  externalCycleId: text("external_cycle_id").notNull(),
  triggerKind: text("trigger_kind").notNull(),
  status: text("status").notNull().default("running"),
  budget: jsonb("budget").$type<Record<string, unknown>>().notNull().default({}),
  metrics: jsonb("metrics").$type<Record<string, unknown>>().notNull().default({}),
  summary: text("summary"),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyExternalCycleUq: uniqueIndex("supervision_cycles_company_external_uq").on(table.companyId, table.sourceKind, table.externalCycleId),
  companyStatusIdx: index("supervision_cycles_company_status_idx").on(table.companyId, table.status, table.startedAt),
}));

export const supervisionInterventions = pgTable("supervision_interventions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  findingId: uuid("finding_id").notNull().references(() => supervisionFindings.id, { onDelete: "cascade" }),
  rootCauseId: uuid("root_cause_id").references(() => supervisionRootCauses.id, { onDelete: "set null" }),
  cycleId: uuid("cycle_id").references(() => supervisionCycles.id, { onDelete: "set null" }),
  admissionDecisionId: uuid("admission_decision_id").references(() => admissionDecisions.id, { onDelete: "set null" }),
  issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
  deliveryId: uuid("delivery_id").references(() => productDeliveries.id, { onDelete: "set null" }),
  ownerAgentId: uuid("owner_agent_id").references(() => agents.id, { onDelete: "set null" }),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("proposed"),
  changeSummary: text("change_summary").notNull(),
  expectedEffect: text("expected_effect").notNull(),
  rollbackPlan: text("rollback_plan").notNull(),
  budget: jsonb("budget").$type<Record<string, unknown>>().notNull().default({}),
  result: jsonb("result").$type<Record<string, unknown>>().notNull().default({}),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  findingStatusIdx: index("supervision_interventions_finding_status_idx").on(table.findingId, table.status, table.createdAt),
  companyStatusIdx: index("supervision_interventions_company_status_idx").on(table.companyId, table.status, table.updatedAt),
}));

export const supervisionRecurrences = pgTable("supervision_recurrences", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  findingId: uuid("finding_id").notNull().references(() => supervisionFindings.id, { onDelete: "cascade" }),
  rootCauseId: uuid("root_cause_id").references(() => supervisionRootCauses.id, { onDelete: "set null" }),
  cycleId: uuid("cycle_id").references(() => supervisionCycles.id, { onDelete: "set null" }),
  runId: uuid("run_id").references(() => heartbeatRuns.id, { onDelete: "set null" }),
  issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
  fingerprint: text("fingerprint").notNull(),
  evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  findingOccurredIdx: index("supervision_recurrences_finding_occurred_idx").on(table.findingId, table.occurredAt),
  companyFingerprintIdx: index("supervision_recurrences_company_fingerprint_idx").on(table.companyId, table.fingerprint, table.occurredAt),
}));

export const supervisionObservationWindows = pgTable("supervision_observation_windows", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  findingId: uuid("finding_id").notNull().references(() => supervisionFindings.id, { onDelete: "cascade" }),
  interventionId: uuid("intervention_id").references(() => supervisionInterventions.id, { onDelete: "set null" }),
  nativeSafeguardId: uuid("native_safeguard_id").references(() => nativeSafeguards.id, { onDelete: "set null" }),
  status: text("status").notNull().default("scheduled"),
  expectedEffect: text("expected_effect").notNull(),
  successCriteria: jsonb("success_criteria").$type<Record<string, unknown>[]>().notNull().default([]),
  measurements: jsonb("measurements").$type<Record<string, unknown>[]>().notNull().default([]),
  conclusion: text("conclusion"),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
  observedAt: timestamp("observed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyStatusIdx: index("supervision_observation_windows_company_status_idx").on(table.companyId, table.status, table.endsAt),
  findingIdx: index("supervision_observation_windows_finding_idx").on(table.findingId, table.status),
}));

export const supervisionEvidenceRefs = pgTable("supervision_evidence_refs", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  findingId: uuid("finding_id").notNull().references(() => supervisionFindings.id, { onDelete: "cascade" }),
  rootCauseId: uuid("root_cause_id").references(() => supervisionRootCauses.id, { onDelete: "set null" }),
  interventionId: uuid("intervention_id").references(() => supervisionInterventions.id, { onDelete: "set null" }),
  cycleId: uuid("cycle_id").references(() => supervisionCycles.id, { onDelete: "set null" }),
  nativeSafeguardId: uuid("native_safeguard_id").references(() => nativeSafeguards.id, { onDelete: "set null" }),
  observationWindowId: uuid("observation_window_id").references(() => supervisionObservationWindows.id, { onDelete: "set null" }),
  sourceKind: text("source_kind").notNull(),
  sourceRef: text("source_ref").notNull(),
  label: text("label"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  findingIdx: index("supervision_evidence_refs_finding_idx").on(table.findingId, table.createdAt),
  companySourceIdx: index("supervision_evidence_refs_company_source_idx").on(table.companyId, table.sourceKind, table.sourceRef),
}));

export const supervisionShadowComparisons = pgTable("supervision_shadow_comparisons", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  externalSource: text("external_source").notNull(),
  externalCycleId: text("external_cycle_id").notNull(),
  nativeCycleId: uuid("native_cycle_id").references(() => supervisionCycles.id, { onDelete: "set null" }),
  status: text("status").notNull().default("compared"),
  matchedFingerprints: jsonb("matched_fingerprints").$type<string[]>().notNull().default([]),
  onlyNative: jsonb("only_native").$type<string[]>().notNull().default([]),
  onlyExternal: jsonb("only_external").$type<string[]>().notNull().default([]),
  severityMismatches: jsonb("severity_mismatches").$type<Array<Record<string, unknown>>>().notNull().default([]),
  metrics: jsonb("metrics").$type<Record<string, unknown>>().notNull().default({}),
  comparedAt: timestamp("compared_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  companyExternalCycleUq: uniqueIndex("supervision_shadow_comparisons_company_cycle_uq").on(table.companyId, table.externalSource, table.externalCycleId),
  companyComparedIdx: index("supervision_shadow_comparisons_company_compared_idx").on(table.companyId, table.comparedAt),
}));
